"""Memo export: Markdown first, then PDF.

A Streamlit app someone has to spin up is a demo format. A PDF that lands in an
inbox is a work format, and it is the thing that gets forwarded into a partner
meeting.

Two invariants:
  - fixed section order, matching the question set file order, so a reader who
    has seen one memo knows where to look in the next one
  - every claim carries a PMID or NCT and the passage it came from, so an
    analyst can verify without re-running anything
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from .biomarker_gating import MARKER_LABELS
from .context import TRIAL_LABEL
from .crypto import harden_outputs, write_secure
from .diligence import MemoResult, SectionResult
from .table_render import markdown_table, pdf_table

DISCLAIMER = (
    "Generated by MedRAG from public sources: PubMed and the ClinicalTrials.gov "
    "registry. Every claim is traceable to a cited passage. This is a research "
    "aid, not investment advice and not medical advice, and citations should be "
    "checked against the original source before they inform a decision."
)


def _fmt_date(stamp: datetime | None) -> str:
    return (stamp or datetime.now()).strftime("%d %B %Y")


def _fda_caveat(prov: dict) -> str | None:
    """One line stating the 510(k) sample against the total, plus the caveat that
    applicant names over-count companies. Without the sample line a memo implies a
    25-clearance sample is the whole category; without the caveat a reader counts
    four names for Imed/Alaris/CareFusion/BD and reads one product line as four
    competitors."""
    n = prov.get("n_fda", 0)
    if not n:
        return None
    store_total = prov.get("n_fda_store_total") or n
    code = prov.get("fda_product_code") or "this category"
    line = f"FDA 510(k) clearances: showing {n} of {store_total} held locally for product code {code}."
    category = prov.get("n_fda_category_total")
    if category and category > store_total:
        line += f" openFDA reports {category} cleared in this category."
    line += (" Distinct applicant names over-count distinct companies — acquisitions "
             "and renames (e.g. Imed → Alaris → CareFusion → BD are one product "
             "line) are not resolved, so a consolidated market can read as more "
             "fragmented than it is.")
    return line


def _pct(n: int, d: int) -> str:
    return f"{100 * n / d:.0f}%" if d else "n/a"


def _aggregate_md(agg: dict | None) -> list[str]:
    """A landscape census, rendered as tables. Every count is over the full match
    set (SQL COUNT); the listed trials are explicitly a sample of the total, and
    NOT_MENTIONED biomarker gating is shown as a gap, never as eligibility."""
    if agg is None:
        return ["_No trial store available — this landscape census could not be computed. "
                "Run `medrag trials` for this indication first._", ""]

    total, readable = agg["total"], agg["eligibility_readable"]
    filt = agg["filters"]
    scope = filt["condition"] or "the indication"
    bm = ", ".join(f"{m} {st}" for m, st in filt["biomarker"]) if filt["biomarker"] else ""
    stat = ", ".join(filt["statuses"]) if filt["statuses"] else "all statuses"

    noun = "trial" if total == 1 else "trials"
    verb = "matches" if total == 1 else "match"
    out = [
        f"**{total} {noun}** {verb} {scope}"
        + (f", gated to {bm}" if bm else "")
        + f" ({stat}). Every count below is computed over all {total} matching records "
          "in the store, not the sample listed at the end.",
        "",
        f"Eligibility text was present and screenable on {readable} of {total} "
        f"({_pct(readable, total)}). The rest are still counted; their biomarker gating "
        "is recorded as NOT_MENTIONED, never assumed eligible.",
        "",
    ]
    if total == 0:
        out.append("_No matching trials in the store. Ingest more with `medrag trials`._")
        out.append("")
        return out

    for title, data in (("phase", agg["by_phase"]), ("status", agg["by_status"]),
                        ("sponsor class", agg["by_sponsor_class"]),
                        ("expected primary completion year", agg["by_completion_year"])):
        out.append(f"**By {title}**")
        out.append("")
        out.extend(markdown_table([title.title(), "Trials"],
                                  [[str(k), str(v)] for k, v in data.items()]))
        out.append("")

    out.append("**Biomarker gating across the field** "
               "(deterministic regex census — NOT_MENTIONED is a gap in the registry text, "
               "not a statement of eligibility)")
    out.append("")
    out.extend(markdown_table(
        ["Marker", "Required", "Excluded", "Not mentioned"],
        [[MARKER_LABELS.get(mk, mk), str(c["REQUIRED"]), str(c["EXCLUDED"]), str(c["NOT_MENTIONED"])]
         for mk, c in agg["by_biomarker"].items()]))
    out.append("")

    shown, dropped = agg["shown"], agg["dropped"]
    out.append(f"**Trials — showing {shown} of {total}**")
    out.append("")
    if dropped:
        out.append(f"> {dropped} matching trial(s) are NOT listed below: this is a sample "
                   f"capped at {shown}. The counts above cover all {total}.")
        out.append("")
    rows = []
    for rec, flags in zip(agg["sample"], agg["sample_flags"]):
        gated = ", ".join(
            f"{MARKER_LABELS.get(m, m)}:{f['status']}"
            for m, f in (flags or {}).items() if f.get("status") != "NOT_MENTIONED"
        ) or "—"
        rows.append([f"`{rec.nct_id}`", rec.brief_title or "(untitled)",
                     rec.phase or "—", rec.overall_status or "—",
                     rec.lead_sponsor or "—", gated])
    out.extend(markdown_table(["NCT", "Title", "Phase", "Status", "Sponsor", "Gating"], rows))
    out.append("")
    return out


def _section_md(s: SectionResult) -> list[str]:
    out = [f"## {s.question.section}", ""]
    out.append(f"*{s.rendered_question}*")
    out.append("")
    if s.aggregate is not None:
        out.extend(_aggregate_md(s.aggregate))
    else:
        out.append(s.answer.text)
        out.append("")

    if s.negative is not None:
        out.append("### Contradicting or unsupportive evidence")
        out.append("")
        if s.negative.stopped_trials:
            out.append("**Trials stopped early**")
            out.append("")
            for st in s.negative.stopped_trials:
                r = st.record
                bits = [f"`{r.nct_id}`", r.overall_status]
                if r.phase:
                    bits.append(r.phase)
                if r.enrollment_count is not None:
                    bits.append(f"n={r.enrollment_count}")
                if r.lead_sponsor:
                    bits.append(r.lead_sponsor)
                out.append(f"- {' · '.join(bits)} — **{st.reason}**")
            out.append("")
        # FDA recalls and adverse events are database facts like the stopped
        # trials, but a recall and a halted trial are different failure modes, so
        # they get their own headings rather than one merged "bad things" list.
        if s.negative.recalls:
            out.append("**FDA recalls**")
            out.append("")
            for r in s.negative.recalls:
                bits = [f"`{r.recall_number}`", r.recall_status or "status not stated"]
                if r.root_cause_description:
                    bits.append(r.root_cause_description)
                if r.recalling_firm:
                    bits.append(r.recalling_firm)
                reason = (r.reason_for_recall or "no reason stated").strip()
                out.append(f"- {' · '.join(bits)} — {reason}")
            out.append("")
        if s.negative.adverse_events:
            total = s.negative.events_shown_of
            out.append(f"**FDA adverse events** (showing {len(s.negative.adverse_events)} "
                       f"of {total} on file, most severe first)")
            out.append("")
            for e in s.negative.adverse_events:
                head = f"`{e.report_number}` · **{e.event_type or 'unspecified'}**"
                if e.brand_name:
                    head += f" · {e.brand_name}"
                problems = ", ".join(e.product_problems[:2]) if e.product_problems else ""
                if problems:
                    head += f" · {problems}"
                out.append(f"- {head}")
            out.append("")
        if s.negative.findings:
            out.append("**Findings against**")
            out.append("")
            for f in s.negative.findings:
                tag = f" *[{f.grade_tag}]*" if f.grade_tag else ""
                out.append(f"- ({f.kind}) {f.point} [{f.citation}]{tag}")
            out.append("")
        if s.negative.is_empty or not s.negative.searched:
            out.append(f"{s.negative.summary()}")
            out.append("")
        if s.negative.note:
            out.append(f"> {s.negative.note}")
            out.append("")

    fda_caveat = _fda_caveat(s.provenance)
    if fda_caveat:
        out.append(f"> {fda_caveat}")
        out.append("")

    if s.evidence:
        out.append("<details><summary>Sources for this section</summary>")
        out.append("")
        for e in s.evidence:
            out.append(f"- {e.bib_line()}")
        out.append("")
        out.append("</details>")
        out.append("")

    prov = s.provenance
    meta = [
        f"route: {s.route.value} ({s.route_method})",
        f"trial records: {prov.get('n_trials', 0)}",
        f"literature: {prov.get('n_literature', 0)}",
        f"validation: {s.validation.summary()}",
    ]
    out.append(f"<sub>{' · '.join(meta)}</sub>")
    out.append("")
    return out


def _memo_title(memo: MemoResult) -> str:
    """Asset-anchored memos title on the asset; an indication-only landscape run
    titles on the indication so the header is not a bare dash."""
    if memo.asset:
        return f"Diligence memo — {memo.asset}"
    return f"Landscape — {memo.indication or 'not specified'}"


def render_markdown(memo: MemoResult, generated: datetime | None = None) -> str:
    cov = memo.coverage()
    lines = [
        f"# {_memo_title(memo)}",
        "",
        f"**Asset:** {memo.asset or 'none (indication-first landscape)'}  ",
        f"**Indication:** {memo.indication or 'not specified'}  ",
        f"**Question set:** {memo.question_set}  ",
        f"**Generated:** {_fmt_date(generated)}  ",
        f"**Model:** {memo.model} · **Embeddings:** {memo.embedder}",
        "",
        "---",
        "",
        "## Coverage",
        "",
        f"- Sections answered with evidence: {cov['sections_with_evidence']}/{cov['sections']}",
        f"- Sections checked for faithfulness: {cov['sections_assessed']}/{cov['sections']}",
        f"- Of those checked, passing: {cov['sections_passing_validation']}/{cov['sections_assessed']}"
        if cov["sections_assessed"] else "- Of those checked, passing: n/a — none were checked",
        f"- Trials found stopped early: {cov['stopped_trials_found']}",
        f"- Contradicting or undercutting findings: {cov['contradicting_findings']}",
        "",
    ]

    if memo.warnings:
        lines.append("**Warnings**")
        lines.append("")
        # Surfaced at the top, not buried: a memo built without the trial store
        # looks complete and is not.
        for w in memo.warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines.append("---")
    lines.append("")

    for s in memo.sections:
        lines.extend(_section_md(s))
        lines.append("---")
        lines.append("")

    lines.append("## Full source list")
    lines.append("")
    seen: set[str] = set()
    for e in memo.all_evidence:
        if e.identifier in seen:
            continue
        seen.add(e.identifier)
        kind = "trial" if e.kind == TRIAL_LABEL else "paper"
        tag = f" [{e.grade_tag}]" if e.grade_tag else ""
        title = e.title or "(untitled)"
        url = f" — {e.url}" if e.url else ""
        lines.append(f"- `{e.identifier}` ({kind}){tag} {title}{url}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*{DISCLAIMER}*")
    lines.append("")

    return "\n".join(lines)


# --------------------------------------------------------------------- PDF

_MD_INLINE = re.compile(r"\*\*(.+?)\*\*|\*(.+?)\*|`(.+?)`")


def _inline_to_rl(text: str) -> str:
    """Convert the small Markdown subset used above into ReportLab markup.

    Escaping happens first: an unescaped ampersand or angle bracket in a paper
    title will otherwise abort the whole PDF build.
    """
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"(?<!\*)\*([^*]+?)\*(?!\*)", r"<i>\1</i>", text)
    text = re.sub(r"`(.+?)`", r"<font face='Courier'>\1</font>", text)
    return text


def _aggregate_pdf(agg, story, styles, Paragraph, Spacer, inch) -> None:
    """PDF rendering of a landscape census: denominator, biomarker census table,
    and a sample table labelled against the total."""
    if agg is None:
        story.append(Paragraph("No trial store available — census not computed.", styles["body"]))
        return
    total, readable = agg["total"], agg["eligibility_readable"]
    filt = agg["filters"]
    bm = ", ".join(f"{m} {st}" for m, st in filt["biomarker"]) if filt["biomarker"] else ""
    stat = ", ".join(filt["statuses"]) if filt["statuses"] else "all statuses"
    story.append(Paragraph(_inline_to_rl(
        f"<b>{total} trials</b> match {filt['condition'] or 'the indication'}"
        + (f", gated to {bm}" if bm else "") + f" ({stat}). Counts are over all {total}, "
        "not the sample below."), styles["body"]))
    if total == 0:
        return
    story.append(Paragraph(_inline_to_rl(
        f"Eligibility text screenable on {readable}/{total} ({_pct(readable, total)}); "
        "the rest are counted with NOT_MENTIONED gating, never assumed eligible."), styles["small"]))
    for title, data in (("Phase", agg["by_phase"]), ("Status", agg["by_status"]),
                        ("Sponsor class", agg["by_sponsor_class"]),
                        ("Primary completion year", agg["by_completion_year"])):
        summary = ", ".join(f"{k}: {v}" for k, v in data.items())
        story.append(Paragraph(_inline_to_rl(f"<b>{title}</b> — {summary}"), styles["small"]))

    story.append(Paragraph("Biomarker gating (NOT_MENTIONED is a gap, not eligibility)", styles["h3"]))
    rows = [[MARKER_LABELS.get(mk, mk), str(c["REQUIRED"]), str(c["EXCLUDED"]), str(c["NOT_MENTIONED"])]
            for mk, c in agg["by_biomarker"].items()]
    story.append(pdf_table(["Marker", "Required", "Excluded", "Not mentioned"],
                           [[_inline_to_rl(str(x)) for x in r] for r in rows],
                           [1.9 * inch, 1.1 * inch, 1.1 * inch, 1.3 * inch], styles["small"]))
    story.append(Spacer(1, 8))

    shown, dropped = agg["shown"], agg["dropped"]
    story.append(Paragraph(f"Trials — showing {shown} of {total}", styles["h3"]))
    if dropped:
        story.append(Paragraph(_inline_to_rl(
            f"{dropped} matching trial(s) not listed: this is a sample capped at {shown}. "
            f"The counts above cover all {total}."), styles["note"]))
    srows = []
    for rec, flags in zip(agg["sample"], agg["sample_flags"]):
        gated = ", ".join(f"{MARKER_LABELS.get(m, m)}:{f['status']}"
                          for m, f in (flags or {}).items() if f.get("status") != "NOT_MENTIONED") or "—"
        srows.append([_inline_to_rl(rec.nct_id), _inline_to_rl(rec.brief_title or "(untitled)"),
                      _inline_to_rl(rec.phase or "—"), _inline_to_rl(rec.overall_status or "—"),
                      _inline_to_rl(rec.lead_sponsor or "—"), _inline_to_rl(gated)])
    story.append(pdf_table(["NCT", "Title", "Phase", "Status", "Sponsor", "Gating"], srows,
                           [0.9 * inch, 2.0 * inch, 0.6 * inch, 1.0 * inch, 1.3 * inch, 1.4 * inch],
                           styles["small"]))
    story.append(Spacer(1, 8))


def render_pdf(memo: MemoResult, path: str | Path, generated: datetime | None = None) -> Path:
    """Build the PDF directly from the memo object.

    Deliberately not a Markdown-to-PDF conversion: rendering from the structured
    result keeps the section order and the citation data authoritative in one
    place, so the two formats cannot drift.
    """
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        HRFlowable,
        ListFlowable,
        ListItem,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
    )

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle("t", parent=base["Title"], fontSize=20, spaceAfter=6),
        "sub": ParagraphStyle("s", parent=base["Normal"], fontSize=9,
                              textColor="#555555", spaceAfter=2),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], fontSize=13,
                             spaceBefore=14, spaceAfter=6),
        "h3": ParagraphStyle("h3", parent=base["Heading3"], fontSize=11,
                             spaceBefore=10, spaceAfter=4, textColor="#8B0000"),
        "body": ParagraphStyle("b", parent=base["Normal"], fontSize=10, leading=14,
                               alignment=TA_LEFT, spaceAfter=6),
        "q": ParagraphStyle("q", parent=base["Normal"], fontSize=10, leading=13,
                            textColor="#333333", leftIndent=10, spaceAfter=8,
                            fontName="Helvetica-Oblique"),
        "small": ParagraphStyle("sm", parent=base["Normal"], fontSize=8, leading=11,
                                textColor="#666666", spaceAfter=4),
        "note": ParagraphStyle("n", parent=base["Normal"], fontSize=9, leading=12,
                               leftIndent=12, textColor="#444444",
                               borderPadding=4, spaceAfter=8),
    }

    story = []
    cov = memo.coverage()

    story.append(Paragraph(_inline_to_rl(_memo_title(memo)), styles["title"]))
    for line in (
        f"Indication: {memo.indication or 'not specified'}",
        f"Question set: {memo.question_set}",
        f"Generated: {_fmt_date(generated)}",
        f"Model: {memo.model} · Embeddings: {memo.embedder}",
    ):
        story.append(Paragraph(_inline_to_rl(line), styles["sub"]))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", color="#cccccc"))

    story.append(Paragraph("Coverage", styles["h2"]))
    story.append(
        ListFlowable(
            [
                ListItem(Paragraph(t, styles["body"]))
                for t in (
                    f"Sections answered with evidence: {cov['sections_with_evidence']}/{cov['sections']}",
                    f"Sections checked for faithfulness: {cov['sections_assessed']}/{cov['sections']}",
                    (f"Of those checked, passing: {cov['sections_passing_validation']}/{cov['sections_assessed']}"
                     if cov["sections_assessed"] else "Of those checked, passing: n/a — none were checked"),
                    f"Trials found stopped early: {cov['stopped_trials_found']}",
                    f"Contradicting or undercutting findings: {cov['contradicting_findings']}",
                )
            ],
            bulletType="bullet",
            leftIndent=16,
        )
    )

    if memo.warnings:
        story.append(Paragraph("Warnings", styles["h3"]))
        for w in memo.warnings:
            story.append(Paragraph(_inline_to_rl(w), styles["body"]))


    for s in memo.sections:
        story.append(Paragraph(_inline_to_rl(s.question.section), styles["h2"]))
        story.append(Paragraph(_inline_to_rl(s.rendered_question), styles["q"]))

        if s.aggregate is not None:
            _aggregate_pdf(s.aggregate, story, styles, Paragraph, Spacer, inch)
        else:
            for para in s.answer.text.split("\n"):
                if para.strip():
                    story.append(Paragraph(_inline_to_rl(para.strip()), styles["body"]))

        if s.negative is not None:
            story.append(Paragraph("Contradicting or unsupportive evidence", styles["h3"]))
            if s.negative.stopped_trials:
                items = []
                for st in s.negative.stopped_trials:
                    r = st.record
                    head = f"<b>{r.nct_id}</b> — {r.overall_status}"
                    if r.phase:
                        head += f", {r.phase}"
                    if r.lead_sponsor:
                        head += f" ({_inline_to_rl(r.lead_sponsor)})"
                    items.append(
                        ListItem(Paragraph(f"{head}<br/>Reason: {_inline_to_rl(st.reason)}",
                                           styles["body"]))
                    )
                story.append(ListFlowable(items, bulletType="bullet", leftIndent=16))
            if s.negative.recalls:
                story.append(Paragraph("FDA recalls", styles["small"]))
                story.append(ListFlowable(
                    [ListItem(Paragraph(
                        f"<b>{_inline_to_rl(r.recall_number)}</b> — "
                        f"{_inline_to_rl(r.recall_status or 'status not stated')}"
                        + (f" ({_inline_to_rl(r.root_cause_description)})"
                           if r.root_cause_description else "")
                        + f"<br/>{_inline_to_rl((r.reason_for_recall or 'no reason stated').strip())}",
                        styles["body"])) for r in s.negative.recalls],
                    bulletType="bullet", leftIndent=16))
            if s.negative.adverse_events:
                story.append(Paragraph(
                    f"FDA adverse events (showing {len(s.negative.adverse_events)} of "
                    f"{s.negative.events_shown_of} on file, most severe first)", styles["small"]))
                story.append(ListFlowable(
                    [ListItem(Paragraph(
                        f"<b>{_inline_to_rl(e.report_number)}</b> — <b>{e.event_type or 'unspecified'}</b>"
                        + (f" · {_inline_to_rl(e.brand_name)}" if e.brand_name else "")
                        + (f" · {_inline_to_rl(', '.join(e.product_problems[:2]))}"
                           if e.product_problems else ""),
                        styles["body"])) for e in s.negative.adverse_events],
                    bulletType="bullet", leftIndent=16))
            if s.negative.findings:
                story.append(
                    ListFlowable(
                        [
                            ListItem(
                                Paragraph(
                                    f"({f.kind}) {_inline_to_rl(f.point)} "
                                    f"[{f.citation}]"
                                    + (f" <i>[{f.grade_tag}]</i>" if f.grade_tag else ""),
                                    styles["body"],
                                )
                            )
                            for f in s.negative.findings
                        ],
                        bulletType="bullet",
                        leftIndent=16,
                    )
                )
            if s.negative.is_empty or not s.negative.searched:
                story.append(Paragraph(_inline_to_rl(s.negative.summary()), styles["note"]))
            if s.negative.note:
                story.append(Paragraph(_inline_to_rl(s.negative.note), styles["note"]))

        fda_caveat = _fda_caveat(s.provenance)
        if fda_caveat:
            story.append(Paragraph(_inline_to_rl(fda_caveat), styles["note"]))

        if s.evidence:
            story.append(Paragraph("Sources for this section", styles["h3"]))
            for e in s.evidence:
                story.append(Paragraph(_inline_to_rl(e.bib_line()), styles["small"]))

        prov = s.provenance
        story.append(
            Paragraph(
                f"route: {s.route.value} ({s.route_method}) · "
                f"trial records: {prov.get('n_trials', 0)} · "
                f"literature: {prov.get('n_literature', 0)} · "
                f"validation: {_inline_to_rl(s.validation.summary())}",
                styles["small"],
            )
        )
        story.append(HRFlowable(width="100%", color="#dddddd"))

    story.append(PageBreak())
    story.append(Paragraph("Full source list", styles["h2"]))
    seen: set[str] = set()
    for e in memo.all_evidence:
        if e.identifier in seen:
            continue
        seen.add(e.identifier)
        kind = "trial" if e.kind == TRIAL_LABEL else "paper"
        tag = f" [{e.grade_tag}]" if e.grade_tag else ""
        story.append(
            Paragraph(
                f"<font face='Courier'>{_inline_to_rl(e.identifier)}</font> ({kind}){tag} "
                f"{_inline_to_rl(e.title or '(untitled)')}"
                + (f"<br/><font size=7>{_inline_to_rl(e.url)}</font>" if e.url else ""),
                styles["small"],
            )
        )

    story.append(Spacer(1, 14))
    story.append(Paragraph(_inline_to_rl(DISCLAIMER), styles["small"]))

    SimpleDocTemplate(
        str(path),
        pagesize=LETTER,
        leftMargin=0.9 * inch,
        rightMargin=0.9 * inch,
        topMargin=0.9 * inch,
        bottomMargin=0.9 * inch,
        title=_memo_title(memo),
        author="MedRAG",
    ).build(story)

    return path


def export(
    memo: MemoResult,
    out_dir: str | Path,
    stem: str | None = None,
    passphrase: str | None = None,
) -> dict[str, Path]:
    """Write both formats and return their paths.

    The two formats get different treatment on purpose. The Markdown is the
    machine-readable copy that sits in `out/` between sessions, so it goes
    through `write_secure` and is encrypted whenever a passphrase is configured —
    the same protection the corpus has always had. The PDF is the artifact people
    circulate; encrypting it would produce a file no reader can open, so it stays
    plaintext at 0600 and the boundary is documented in SECURITY.md rather than
    pretended away.

    Passing no passphrase while MEDRAG_ENCRYPT is set raises from `write_secure`
    rather than silently writing cleartext. That is the existing fail-closed
    guard and it is deliberate: a memo that quietly loses its encryption is worse
    than a run that stops and says so.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = stem or re.sub(r"[^a-z0-9]+", "-", (memo.asset or memo.indication).lower()).strip("-") or "memo"

    md_path = out_dir / f"{stem}-diligence.md"
    write_secure(md_path, render_markdown(memo).encode("utf-8"), passphrase)
    pdf_path = render_pdf(memo, out_dir / f"{stem}-diligence.pdf")
    harden_outputs(out_dir, md_path, pdf_path)
    return {"markdown": md_path, "pdf": pdf_path}
