"""Memo export: Markdown first, then PDF.

A Streamlit app someone has to spin up is a demo format. A PDF that lands in an
inbox is a work format, and it is the thing that gets forwarded into a partner
meeting.

Two invariants:
  - fixed section order, matching the question set file order, so a reader who
    has seen one memo knows where to look in the next one
  - every claim carries a PMID or NCT and the passage it came from, so an
    analyst can verify without re-running anything
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from .context import LIT_LABEL, TRIAL_LABEL
from .diligence import MemoResult, SectionResult

DISCLAIMER = (
    "Generated by MedRAG from public sources: PubMed and the ClinicalTrials.gov "
    "registry. Every claim is traceable to a cited passage. This is a research "
    "aid, not investment advice and not medical advice, and citations should be "
    "checked against the original source before they inform a decision."
)


def _fmt_date(stamp: datetime | None) -> str:
    return (stamp or datetime.now()).strftime("%d %B %Y")


def _section_md(s: SectionResult) -> list[str]:
    out = [f"## {s.question.section}", ""]
    out.append(f"*{s.rendered_question}*")
    out.append("")
    out.append(s.answer.text)
    out.append("")

    if s.negative is not None:
        out.append("### Contradicting or unsupportive evidence")
        out.append("")
        if s.negative.stopped_trials:
            out.append("**Trials stopped early**")
            out.append("")
            for st in s.negative.stopped_trials:
                r = st.record
                bits = [f"`{r.nct_id}`", r.overall_status]
                if r.phase:
                    bits.append(r.phase)
                if r.enrollment_count is not None:
                    bits.append(f"n={r.enrollment_count}")
                if r.lead_sponsor:
                    bits.append(r.lead_sponsor)
                out.append(f"- {' · '.join(bits)} — **{st.reason}**")
            out.append("")
        if s.negative.findings:
            out.append("**Findings against**")
            out.append("")
            for f in s.negative.findings:
                tag = f" *[{f.grade_tag}]*" if f.grade_tag else ""
                out.append(f"- ({f.kind}) {f.point} [{f.citation}]{tag}")
            out.append("")
        if s.negative.is_empty or not s.negative.searched:
            out.append(f"{s.negative.summary()}")
            out.append("")
        if s.negative.note:
            out.append(f"> {s.negative.note}")
            out.append("")

    if s.evidence:
        out.append("<details><summary>Sources for this section</summary>")
        out.append("")
        for e in s.evidence:
            out.append(f"- {e.bib_line()}")
        out.append("")
        out.append("</details>")
        out.append("")

    prov = s.provenance
    meta = [
        f"route: {s.route.value} ({s.route_method})",
        f"trial records: {prov.get('n_trials', 0)}",
        f"literature: {prov.get('n_literature', 0)}",
        f"validation: {s.validation.summary()}",
    ]
    out.append(f"<sub>{' · '.join(meta)}</sub>")
    out.append("")
    return out


def render_markdown(memo: MemoResult, generated: datetime | None = None) -> str:
    cov = memo.coverage()
    lines = [
        f"# Diligence memo — {memo.asset}",
        "",
        f"**Indication:** {memo.indication or 'not specified'}  ",
        f"**Question set:** {memo.question_set}  ",
        f"**Generated:** {_fmt_date(generated)}  ",
        f"**Model:** {memo.model} · **Embeddings:** {memo.embedder}",
        "",
        "---",
        "",
        "## Coverage",
        "",
        f"- Sections answered with evidence: {cov['sections_with_evidence']}/{cov['sections']}",
        f"- Sections checked for faithfulness: {cov['sections_assessed']}/{cov['sections']}",
        f"- Of those checked, passing: {cov['sections_passing_validation']}/{cov['sections_assessed']}"
        if cov["sections_assessed"] else "- Of those checked, passing: n/a — none were checked",
        f"- Trials found stopped early: {cov['stopped_trials_found']}",
        f"- Contradicting or undercutting findings: {cov['contradicting_findings']}",
        "",
    ]

    if memo.warnings:
        lines.append("**Warnings**")
        lines.append("")
        # Surfaced at the top, not buried: a memo built without the trial store
        # looks complete and is not.
        for w in memo.warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines.append("---")
    lines.append("")

    for s in memo.sections:
        lines.extend(_section_md(s))
        lines.append("---")
        lines.append("")

    lines.append("## Full source list")
    lines.append("")
    seen: set[str] = set()
    for e in memo.all_evidence:
        if e.identifier in seen:
            continue
        seen.add(e.identifier)
        kind = "trial" if e.kind == TRIAL_LABEL else "paper"
        tag = f" [{e.grade_tag}]" if e.grade_tag else ""
        title = e.title or "(untitled)"
        url = f" — {e.url}" if e.url else ""
        lines.append(f"- `{e.identifier}` ({kind}){tag} {title}{url}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*{DISCLAIMER}*")
    lines.append("")

    return "\n".join(lines)


# --------------------------------------------------------------------- PDF

_MD_INLINE = re.compile(r"\*\*(.+?)\*\*|\*(.+?)\*|`(.+?)`")


def _inline_to_rl(text: str) -> str:
    """Convert the small Markdown subset used above into ReportLab markup.

    Escaping happens first: an unescaped ampersand or angle bracket in a paper
    title will otherwise abort the whole PDF build.
    """
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"(?<!\*)\*([^*]+?)\*(?!\*)", r"<i>\1</i>", text)
    text = re.sub(r"`(.+?)`", r"<font face='Courier'>\1</font>", text)
    return text


def render_pdf(memo: MemoResult, path: str | Path, generated: datetime | None = None) -> Path:
    """Build the PDF directly from the memo object.

    Deliberately not a Markdown-to-PDF conversion: rendering from the structured
    result keeps the section order and the citation data authoritative in one
    place, so the two formats cannot drift.
    """
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        HRFlowable,
        ListFlowable,
        ListItem,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
    )

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle("t", parent=base["Title"], fontSize=20, spaceAfter=6),
        "sub": ParagraphStyle("s", parent=base["Normal"], fontSize=9,
                              textColor="#555555", spaceAfter=2),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], fontSize=13,
                             spaceBefore=14, spaceAfter=6),
        "h3": ParagraphStyle("h3", parent=base["Heading3"], fontSize=11,
                             spaceBefore=10, spaceAfter=4, textColor="#8B0000"),
        "body": ParagraphStyle("b", parent=base["Normal"], fontSize=10, leading=14,
                               alignment=TA_LEFT, spaceAfter=6),
        "q": ParagraphStyle("q", parent=base["Normal"], fontSize=10, leading=13,
                            textColor="#333333", leftIndent=10, spaceAfter=8,
                            fontName="Helvetica-Oblique"),
        "small": ParagraphStyle("sm", parent=base["Normal"], fontSize=8, leading=11,
                                textColor="#666666", spaceAfter=4),
        "note": ParagraphStyle("n", parent=base["Normal"], fontSize=9, leading=12,
                               leftIndent=12, textColor="#444444",
                               borderPadding=4, spaceAfter=8),
    }

    story = []
    cov = memo.coverage()

    story.append(Paragraph(f"Diligence memo — {_inline_to_rl(memo.asset)}", styles["title"]))
    for line in (
        f"Indication: {memo.indication or 'not specified'}",
        f"Question set: {memo.question_set}",
        f"Generated: {_fmt_date(generated)}",
        f"Model: {memo.model} · Embeddings: {memo.embedder}",
    ):
        story.append(Paragraph(_inline_to_rl(line), styles["sub"]))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", color="#cccccc"))

    story.append(Paragraph("Coverage", styles["h2"]))
    story.append(
        ListFlowable(
            [
                ListItem(Paragraph(t, styles["body"]))
                for t in (
                    f"Sections answered with evidence: {cov['sections_with_evidence']}/{cov['sections']}",
                    f"Sections checked for faithfulness: {cov['sections_assessed']}/{cov['sections']}",
                    (f"Of those checked, passing: {cov['sections_passing_validation']}/{cov['sections_assessed']}"
                     if cov["sections_assessed"] else "Of those checked, passing: n/a — none were checked"),
                    f"Trials found stopped early: {cov['stopped_trials_found']}",
                    f"Contradicting or undercutting findings: {cov['contradicting_findings']}",
                )
            ],
            bulletType="bullet",
            leftIndent=16,
        )
    )

    if memo.warnings:
        story.append(Paragraph("Warnings", styles["h3"]))
        for w in memo.warnings:
            story.append(Paragraph(_inline_to_rl(w), styles["body"]))

    for s in memo.sections:
        story.append(Paragraph(_inline_to_rl(s.question.section), styles["h2"]))
        story.append(Paragraph(_inline_to_rl(s.rendered_question), styles["q"]))

        for para in s.answer.text.split("\n"):
            if para.strip():
                story.append(Paragraph(_inline_to_rl(para.strip()), styles["body"]))

        if s.negative is not None:
            story.append(Paragraph("Contradicting or unsupportive evidence", styles["h3"]))
            if s.negative.stopped_trials:
                items = []
                for st in s.negative.stopped_trials:
                    r = st.record
                    head = f"<b>{r.nct_id}</b> — {r.overall_status}"
                    if r.phase:
                        head += f", {r.phase}"
                    if r.lead_sponsor:
                        head += f" ({_inline_to_rl(r.lead_sponsor)})"
                    items.append(
                        ListItem(Paragraph(f"{head}<br/>Reason: {_inline_to_rl(st.reason)}",
                                           styles["body"]))
                    )
                story.append(ListFlowable(items, bulletType="bullet", leftIndent=16))
            if s.negative.findings:
                story.append(
                    ListFlowable(
                        [
                            ListItem(
                                Paragraph(
                                    f"({f.kind}) {_inline_to_rl(f.point)} "
                                    f"[{f.citation}]"
                                    + (f" <i>[{f.grade_tag}]</i>" if f.grade_tag else ""),
                                    styles["body"],
                                )
                            )
                            for f in s.negative.findings
                        ],
                        bulletType="bullet",
                        leftIndent=16,
                    )
                )
            if s.negative.is_empty or not s.negative.searched:
                story.append(Paragraph(_inline_to_rl(s.negative.summary()), styles["note"]))
            if s.negative.note:
                story.append(Paragraph(_inline_to_rl(s.negative.note), styles["note"]))

        if s.evidence:
            story.append(Paragraph("Sources for this section", styles["h3"]))
            for e in s.evidence:
                story.append(Paragraph(_inline_to_rl(e.bib_line()), styles["small"]))

        prov = s.provenance
        story.append(
            Paragraph(
                f"route: {s.route.value} ({s.route_method}) · "
                f"trial records: {prov.get('n_trials', 0)} · "
                f"literature: {prov.get('n_literature', 0)} · "
                f"validation: {_inline_to_rl(s.validation.summary())}",
                styles["small"],
            )
        )
        story.append(HRFlowable(width="100%", color="#dddddd"))

    story.append(PageBreak())
    story.append(Paragraph("Full source list", styles["h2"]))
    seen: set[str] = set()
    for e in memo.all_evidence:
        if e.identifier in seen:
            continue
        seen.add(e.identifier)
        kind = "trial" if e.kind == TRIAL_LABEL else "paper"
        tag = f" [{e.grade_tag}]" if e.grade_tag else ""
        story.append(
            Paragraph(
                f"<font face='Courier'>{_inline_to_rl(e.identifier)}</font> ({kind}){tag} "
                f"{_inline_to_rl(e.title or '(untitled)')}"
                + (f"<br/><font size=7>{_inline_to_rl(e.url)}</font>" if e.url else ""),
                styles["small"],
            )
        )

    story.append(Spacer(1, 14))
    story.append(Paragraph(_inline_to_rl(DISCLAIMER), styles["small"]))

    SimpleDocTemplate(
        str(path),
        pagesize=LETTER,
        leftMargin=0.9 * inch,
        rightMargin=0.9 * inch,
        topMargin=0.9 * inch,
        bottomMargin=0.9 * inch,
        title=f"Diligence memo — {memo.asset}",
        author="MedRAG",
    ).build(story)

    return path


def export(memo: MemoResult, out_dir: str | Path, stem: str | None = None) -> dict[str, Path]:
    """Write both formats and return their paths."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = stem or re.sub(r"[^a-z0-9]+", "-", memo.asset.lower()).strip("-") or "memo"

    md_path = out_dir / f"{stem}-diligence.md"
    md_path.write_text(render_markdown(memo), encoding="utf-8")
    pdf_path = render_pdf(memo, out_dir / f"{stem}-diligence.pdf")
    return {"markdown": md_path, "pdf": pdf_path}
